/* Generated By:JJTree: Do not edit this line. ASTDecrease.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dev.ryanramsdell.jjtree;

import dev.ryanramsdell.enums.StitchType;
import dev.ryanramsdell.enums.DecreaseType;

public
class ASTDecrease extends dev.ryanramsdell.jjtree.SimpleNode {
  private StitchType type;
  private int num;
  private DecreaseType decreaseType;
  public ASTDecrease(int id) {
    super(id);
  }

  public ASTDecrease(Knit p, int id) {
    super(p, id);
  }

  public void setType(StitchType type) {
    this.type = type;
  }
  public void setNum(int num) {
    this.num = num;
  }
  public void setDecreaseType(DecreaseType type) {
    this.decreaseType = type;
  }
  public StitchType getType() {
    return type;
  }

  public int getNum() {
    return num;
  }

  public DecreaseType getDecreaseType() {
    return this.decreaseType;
  }
  public String toString() {
    return "Decrease " + this.type + " " + this.num + " " + this.decreaseType;
  }

}
/* JavaCC - OriginalChecksum=6f97654dda01e79fd3041833f2a74c51 (do not edit this line) */
