/* Generated By:JJTree: Do not edit this line. ASTDecrease.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package dev.ryanramsdell.jjtree;

import dev.ryanramsdell.enums.StitchType;

public
class ASTDecrease extends dev.ryanramsdell.jjtree.SimpleNode {
  private StitchType type;
  private int num;
  public ASTDecrease(int id) {
    super(id);
  }

  public ASTDecrease(Knit p, int id) {
    super(p, id);
  }

  public void setType(StitchType type) {
    this.type = type;
  }
  public void setNum(int num) {
    this.num = num;
  }

  public StitchType getType() {
    return type;
  }

  public int getNum() {
    return num;
  }

  public String toString() {
    return "Decrease " + this.type + " " + this.num;
  }

}
/* JavaCC - OriginalChecksum=6f97654dda01e79fd3041833f2a74c51 (do not edit this line) */
